### ISSUE TITLE
Support Python 2 - 'module' object has no attribute 'TemporaryDirectory

### ISSUE THREAD

**Issue by dmp1ce** [kewlfft/ansible-aur#18]
I am using the install trizen example in a role called aur_builder here:

```
# AUR builder related tasks
- name: Create aur_builder user
  user:
    name: aur_builder
    group: wheel
- name: Allow aur_builder to run pacman as root
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'

# Install trizen using makepkg, skip if trizen is already installed
- name: Install trizen
  aur: name=trizen use=makepkg skip_installed=true
  become: yes
  become_user: aur_builder
```

and I'm getting the following error.

```
TASK [aur_builder : Install trizen] ********************************************
fatal: [default]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_UQa5Xn/ansible_module_aur.py\", line 255, in <module>\r\n    main()\r\n  File \"/tmp/ansible_UQa5Xn/ansible_module_aur.py\", line 251, in main\r\n    install_packages(module, params['name'], use, params['skip_installed'], params['aur_only'])\r\n  File \"/tmp/ansible_UQa5Xn/ansible_module_aur.py\", line 180, in install_packages\r\n    rc, out, err = install_with_makepkg(module, package)\r\n  File \"/tmp/ansible_UQa5Xn/ansible_module_aur.py\", line 135, in install_with_makepkg\r\n    with tempfile.TemporaryDirectory() as tmpdir:\r\nAttributeError: 'module' object has no attribute 'TemporaryDirectory'\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

Am I missing something or is this a new bug?

My version of ansible is:

```
ansible --version
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/david/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 13:11:40) [GCC 8.1.1 20180531]
```
