### ISSUE TITLE
Wrap the module in a role

### ISSUE THREAD

**Issue by pallxk** [kewlfft/ansible-aur#28]
What about wrapping this module into a role and publish it to ansible galaxy? So that end users or other role developers can easily consume it.

See https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#embedding-modules-and-plugins-in-roles

For end users, they can do something like:

```yml
# playbook.yml
- hosts: localhost
  roles:
  - name: kewlfft.aur
  tasks:
  - aur:
      name: xxx
```

For role developers:

```yml
# meta/main.yml
dependencies:
- kewlfft.aur
```

```yml
# tasks/main.yml
- aur:
    name: xxx
```
