### ISSUE TITLE
Add noconfirm and noedit

### ISSUE THREAD

**Issue by DanSman** [kewlfft/ansible-aur#49]
Hey

I am having some problems setting --noconfirm and --noedit when I want to perform a system update. Is it not just 
```
    extra_args: 
      --noconfirm 
      --noedit
```

I just started using Ansible and am still learning it. 

Thanks
Dan

**Comment by nekwebdev** [comment]
Looking at the code:
```
    extra_args:
        description:
            - Arguments to pass to the tool.
              Requires that the 'use' option be set to something other than 'auto'.
        type: str
```

So in your case I would do

`extra_args: "--noconfirm --noedit"`

Hope it helps
