### ISSUE TITLE
Installing an already installed package with paru gives an error

### ISSUE THREAD

**Issue by 33Fraise33** [kewlfft/ansible-aur#54]
Hello,

Running the following play gives an error that there is nothing to do, this errors the play and stops the playbook. This should be ok and ignored. 

```
- name: install paru
  aur:
    name:
      - paru-bin # aur helper
    state: latest
```

```
fatal: [arch_vm]: FAILED! => {"changed": false, "cmd": "env LC_ALL=C paru -S --noconfirm --needed --cleanafter paru-bin", "msg": ":: paru-bin-1.3.0-1 is up to date -- skipping", "rc": 1, "stderr": ":: paru-bin-1.3.0-1 is up to date -- skipping\n", "stderr_lines": [":: paru-bin-1.3.0-1 is up to date -- skipping"], "stdout": ":: Resolving dependencies...\n there is nothing to do\n", "stdout_lines": [":: Resolving dependencies...", " there is nothing to do"]}
```
