### ISSUE TITLE
Reinstall doesn't report change

### ISSUE THREAD

**Issue by jp1995** [kewlfft/ansible-aur#77]
```
- name: Test install
  kewlfft.aur.aur:
    name: units
    state: present
    use: yay
  become: yes
  become_user: aur_builder
  
- name: Remove test package
  community.general.pacman:
    name: units
    state: removed
    remove_nosave: true
    
- name: Test reinstall
  kewlfft.aur.aur:
    name: units
    state: present
    use: yay
  become: yes
  become_user: aur_builder
```

produces:

```
TASK [test : Test install] ***************************************************************
changed: [iota]

TASK [test : Remove test package] ********************************************************
--- before
+++ after
@@ -1 +0,0 @@
-units-2.22-2

changed: [iota]

TASK [test : Test reinstall] *************************************************************
ok: [iota]                                                                                               
```

wheras expected behaviour would be:
```
TASK [test : Test reinstall] *************************************************************
changed: [iota]                                                                                         
```

I figured maybe this had to do with cached packages, but none of the package I tested with (grafana-bin, units) cached anything in `/var/cache/pacman/pkg` or `~/.cache/yay/` and reinstall is always recompiling too.

Manually running `pacman -Rdd` or `pacman -Rns` doesn't work either.

The `community.general.pacman` module does have this expected behaviour on reinstall.

Not a pacman / arch expert by any means, but Is there something specific I'm supposed to do here to solve this, or is this a bug?
